# Generated by Django 3.0.2 on 2020-04-13 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200411_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricepoint',
            name='alpha',
            field=models.DecimalField(decimal_places=4, default=10, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pricepoint',
            name='beta',
            field=models.DecimalField(decimal_places=4, default=10, max_digits=12),
            preserve_default=False,
        ),
    ]
