# Generated by Django 3.0.2 on 2020-04-14 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200413_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='current_price',
        ),
        migrations.AddField(
            model_name='item',
            name='current_price_point',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.PricePoint'),
        ),
    ]
