# Generated by Django 3.0.2 on 2020-04-24 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200414_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricepoint',
            name='demand',
        ),
    ]
