# Generated by Django 3.0.2 on 2020-04-24 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_pricepoint_demand'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Item')),
                ('price_point', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.PricePoint')),
            ],
        ),
    ]
