# Generated by Django 3.0.2 on 2020-04-24 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_saleslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleslog',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='saleslog',
            name='price_point',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
            preserve_default=False,
        ),
    ]
