# Generated by Django 3.0.2 on 2020-04-24 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200424_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleslog',
            name='price_point',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.PricePoint'),
        ),
    ]
