# Generated by Django 3.0.2 on 2020-05-04 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200424_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleslog',
            name='is_new',
        ),
        migrations.AddField(
            model_name='saleslog',
            name='demand',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
